[WIP] feat: multiple media layers, moving
und3fined-v01d/webxr-layers pull request #21
Opened 2021-03-07 07:27 UTC by zhixiangteoh

Changes:
1. Added grey intersecting point dot on toolbars as additional visual cue 
2. Added `MediaLayer`, `GlassLayer` classes
     - Each `MediaLayer` is tagged to one `Toolbar`
3. Added `createMediaLayer()` method in `MediaLayerManager` that creates `MediaLayer` objects
4. Updated `multiple-layers.js` to create separate independent video DOM elements per `MediaLayer`
     - Each layer's toolbar controls only affect that layer's video
5. [WIP] Create glass layers to handle moving and resizing

2021-03-07 08:57 UTC, und3fined-v01d commented
> 
> 
> Changes:
> 
>     1. Added grey intersecting point dot on toolbars as additional visual cue
> 
>     2. Added `MediaLayer`, `GlassLayer` classes
>        
>        * Each `MediaLayer` is tagged to one `Toolbar`
> 
>     3. Added `createMediaLayer()` method in `MediaLayerManager` that creates `MediaLayer` objects
> 
>     4. Updated `multiple-layers.js` to create separate independent video DOM elements per `MediaLayer`
>        
>        * Each layer's toolbar controls only affect that layer's video
> 
>     5. [WIP] Create glass layers to handle moving and resizing

This patch is doing too many things. Let's create a separate patch to handle moving

2021-03-07 09:11 UTC, und3fined-v01d requested changes

2021-03-07 09:11 UTC, und3fined-v01d commented on util/Toolbar.js
> +    createToolbarGroup(rotateXAngle, { position: { x, y, z } }) {
Destructure this within the function. It will help for error handling later

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +        this.intersectPoint = this.createIntersectPoint();
Let us remove this for now. There is already a highlight feature on toolbar intersection. We can add this later when needed.

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +            mediaLayer.updateOnRender(xr.isPresenting);
Move the xr.isPresenting check outside the foor loop. This way we run the loop only if xr is presenting

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +                this.handleToolbarIntersections(
This will not work if we have multiple equirect layers. We should modify this method to a more general case

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +                layers: [equirect.videoLayer, session.renderState.layers[0]],
Call it just layer instead of "videoLayer"

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +            this.handleTriggerPress(controller);
Let's called this selectPress since thats the name of the default event too

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +        line.scale.z = 1;
Why has the scale been reduced?

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +        const geometry = new THREE.CircleGeometry(0.02, 10);
Let's remove this for now

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +    handleTriggerPress(controller) {
Name this handleSelectPress

2021-03-07 09:11 UTC, und3fined-v01d commented on apps/equirect-buttons.js
> +        let isAllToolbarsHidden = true;
this should be areAllToolbarsHidden

2021-03-08 06:30 UTC, zhixiangteoh commented on apps/equirect-buttons.js
> +                this.handleToolbarIntersections(
This code for `equirect-buttons.js` is not the most updated; support for multiple layers (mainly quad layers) is in `multiple-layers.js`

2021-03-08 06:31 UTC, zhixiangteoh commented on apps/equirect-buttons.js
> +        this.intersectPoint = this.createIntersectPoint();
I think this is helpful for quad layers when we want to arbitrarily place quad layers far down z axis and also move them arbitrarily. The controller ray should not be so long as to be able to reach them (e.g. the Oculus shell ray is short), and highlighting is not easy to see where you are pointing if the ray does not directly touch the toolbar.

2021-03-08 06:32 UTC, zhixiangteoh commented on util/Toolbar.js
> +        this.toolbarGroup = this.createToolbarGroup(
Makes sense. In fact ui position does not really change, it's the toolbarGroup position that changes depending on where you want to place the whole toolbar.

2021-03-08 06:33 UTC, zhixiangteoh commented on apps/equirect-buttons.js
> +        let isAllToolbarsHidden = true;
Makes sense.

2021-03-08 06:36 UTC, zhixiangteoh commented
> > Changes:
> > ```
> > 1. Added grey intersecting point dot on toolbars as additional visual cue
> > 
> > 2. Added `MediaLayer`, `GlassLayer` classes
> >    
> >    * Each `MediaLayer` is tagged to one `Toolbar`
> > 
> > 3. Added `createMediaLayer()` method in `MediaLayerManager` that creates `MediaLayer` objects
> > 
> > 4. Updated `multiple-layers.js` to create separate independent video DOM elements per `MediaLayer`
> >    
> >    * Each layer's toolbar controls only affect that layer's video
> > 
> > 5. [WIP] Create glass layers to handle moving and resizing
> > ```
> 
> This patch is doing too many things. Let's create a separate patch to handle moving

Agreed. Will split into different branches/PRs.

2021-03-22 15:34 UTC, zhixiangteoh commented
Closed by #24

2021-03-22 15:34 UTC, closed without merging