Change videos to use sloth videos
und3fined-v01d/webxr-layers pull request #26
Opened 2021-03-24 04:46 UTC by zhixiangteoh

Stereo top-bottom (360 deg): https://d25a56pc18k0co.cloudfront.net/sloths_binaural_3840x2160_360_3D_v2_injected.mp4
Stereo-left-right (180 deg): https://d25a56pc18k0co.cloudfront.net/sloths_binaural_3840_180_3D-injected.mp4

2021-03-31 11:46 UTC, und3fined-v01d requested changes

2021-03-31 11:46 UTC, und3fined-v01d commented on apps/simple-video-layers/multiple-layers.js
> +    "https://d25a56pc18k0co.cloudfront.net/sloths_binaural_3840x2160_360_3D_v2_injected.mp4";
lets download this instead of a url

2021-03-31 11:46 UTC, und3fined-v01d requested changes

2021-03-31 11:46 UTC, und3fined-v01d commented on apps/simple-video-layers/multiple-layers.js
> +        video.preload = "auto";
don't need this if we download the videos

2021-03-31 19:36 UTC, zhixiangteoh commented on apps/simple-video-layers/multiple-layers.js
> +    "https://d25a56pc18k0co.cloudfront.net/sloths_binaural_3840x2160_360_3D_v2_injected.mp4";
Don't download it!!! Trust me I tried and it's too big... even spent some time lowering quality to 1080p and trimming video but it's still too big to load.

2021-03-31 19:36 UTC, zhixiangteoh commented on apps/simple-video-layers/multiple-layers.js
> +        video.preload = "auto";
See above.

2021-04-12 23:18 UTC, cabanier commented on apps/simple-video-layers/multiple-layers.js
> +    "https://d25a56pc18k0co.cloudfront.net/sloths_binaural_3840x2160_360_3D_v2_injected.mp4";
Yes, these files are very big so you can't host them on github.
Also, if you downsample them, they will no longer look good.

2021-04-12 23:19 UTC, cabanier commented
I think this can be merged once the conflicts are resolved?

2021-04-13 14:41 UTC, merged